### ISSUE TITLE
Consider return proxy from proxy.update method

### ISSUE THREAD

**Issue by Kureev** [gaearon/react-proxy#18]
Hi Dan,

I find it a bit weird, that `proxy.update` returns list of proxied elements. Probably, it does make sense to return `proxy` instance instead and expose `mountedInstances` as an export parameter like this:

```javascript
import { createProxy, getForceUpdate, mountedInstances } from 'react-proxy';
```

What do you think about it?

**Comment by gaearon** [comment]
`mountedInstance` depends on a specific class, we can't export it globally.

I'm not sure `proxy.update()` returning the proxy itself is very useful. What would you do with it? Sounds like “fluent APIs” which I think are often misguided and hide the effects of the methods.

What I wanted to make clear with this API is that `proxy.get()` is always the same thing, and thus there's no point to returning it many times. On the other hand, the *only* thing you want to do after calling `update` is to force-update the mounted instances. In my view, for this reason, returning them from `update()` makes sense: it's a reminder you need to do something about them. It's also a bit like `db.insert()` might return the number of affected records.

**Comment by Kureev** [comment]
Okay, I see your point. But in this case I'd ideally like to see something like:
```javascript
var forceUpdate = proxy.update(SomeComponentV2);
forceUpdate();
```

Do we have any benefits of having `mountedInstances) besides invoking `forceUpdate` over them?

**Comment by gaearon** [comment]
>Maybe also make sense to return only updated proxy to be able to re-render only it's node?

There may be many instances of the same updated class, that's why we return an array.

>Do we have any benefits of having mountedInstances besides invoking forceUpdate over them?

I wanted to give consumer freedom to experiment with handling errors, for example. The consumer might wrap each `forceUpdate` into independent `try-catch` instead of performing a fail-fast update, somehow preprocess the instances, or maybe even `update()` back to the previous proxy if an error occurs.

This is a low-level library so I want consumer to have as much choice as possible, with projects like React Hot Loader choosing something sane.

**Comment by Kureev** [comment]
Nice, thanks for detailed explanation :+1:
