### ISSUE TITLE
Proxy'd component missing setState in IE 9/10

### ISSUE THREAD

**Issue by kentor** [gaearon/react-proxy#27]
```js
const React = require('react');
const { createProxy } = require('react-proxy');

const Component = React.createClass({
  getInitialState() {
    return { text: 'hi' };
  },

  componentDidMount() {
    this.setState({ text: 'hey' });
  },

  render() {
    return <span>{this.state.text}</span>;
  },
});

const proxy = createProxy(Component);
const Proxy = proxy.get();

const element = <Proxy />;

React.render(element, document.getElementById('root'));
```

Only in IE9:
```
Warning: Something is calling a React component directly. Use a factory or JSX instead. See: https://fb.me/react-legacyfactory 
SCRIPT438: Object doesn't support property or method 'setState'
```

did not test 10, ok in 11, Edge, Chrome, FF. testing repo: https://github.com/kentor/react-transform-hmr-ie9

Pretty stumped on this one... 

![screen shot 2015-09-23 at 1 58 29 pm](https://cloud.githubusercontent.com/assets/240493/10058698/b842f278-61fb-11e5-8f21-1530e10f3f22.png)

I put a debugger on where the Warning would have been emitted and went up the call stack to see what's different from the other browsers. Also here `this instanceof Constructor` returns `false` in ie9 vs other browsers.

![screen shot 2015-09-23 at 1 59 35 pm](https://cloud.githubusercontent.com/assets/240493/10058708/c4fb4c36-61fb-11e5-9d47-93e6557432ce.png)

This is a place of suspicion.

![screen shot 2015-09-23 at 2 00 08 pm](https://cloud.githubusercontent.com/assets/240493/10058744/f530d04c-61fb-11e5-850c-fa4725182ef0.png)

 I set the `internalInstance` to a variable and then went down a stack frame

![screen shot 2015-09-23 at 2 00 24 pm](https://cloud.githubusercontent.com/assets/240493/10058762/ff82a688-61fb-11e5-9e2b-550e767a1386.png)

`this` which should have been the caller, `internalInstance`, is not the case in ie9 vs other browsers.

**Comment by gaearon** [comment]
Woah woah, that's the best issue description I've seen in a while. :+1: 

I think it happens because IE did not support assigning `__proto__` before IE11.
We [rely on `__proto__` assignment](https://github.com/gaearon/react-proxy/blob/b429d7285f4055fd73c891d688f35e145c86dda9/src/createPrototypeProxy.js#L144-L145) to set up the prototype chain to point to the new version of the class.

I'm not sure if there's any meaningful fallback we could use..

**Comment by kentor** [comment]
Yep, that lack of `__proto__` assignment would do it and it doesn't look like there are any workarounds for IE < 11.

**Comment by glenjamin** [comment]
If you can detect it, you can fall back to prop copying.

**Comment by okonet** [comment]
I can confirm this is also happening in IE10. Any workaround for this?

**Comment by gaearon** [comment]
The biggest issue for me is that I don't have IE at hand, and can't verify whether any changes to the code fix this. If you'd like to work on this please look here:

https://github.com/gaearon/react-proxy/blob/d1b975d47b58d086851c4f2b88622f9cb2cbef00/src/createClassProxy.js#L88-L89

This is the line which, from what I understand, has no effect in IE < 11 because it doesn't support `__proto__`. If there is a way to detect this at runtime and manually copy descriptors defined on base class (`React.Component` and potentially other base classes) right onto the `ProxyClass`, that would probably solve the issue. But of course you'd need IE to actually verify whether the problem is fixed.

**Comment by nhunzaker** [comment]
Just hit this. Testing on IE10 using the VMWare image via https://dev.modern.ie/tools/vms/mac/. I can't dig into it at the moment, but I thought I'd plug site in the interim.

**Comment by SimenB** [comment]
Babel docs contains a caveat about `__proto__` in IE < 11, maybe using the transform helps? https://babeljs.io/docs/advanced/caveats/#classes-10-and-below-

**Comment by seantimm** [comment]
I didn't have any luck getting the transform to work.  Anyone else?

**Comment by SimenB** [comment]
I've also noticed that the transform in the docs is now a plugin, you can try that instead of `optional`?

https://www.npmjs.com/package/babel-plugin-proto-to-assign

**Comment by kentor** [comment]
The plugin does transform that line from `proxy.__proto__ = next` to `_defaults(proxy, next);`, but it seems like what that does is a shallow copy of the properties from `next` to `proxy`. In other words `setState` is still undefined because it is higher up in the prototype chain, (on `next.__proto__`) so using that transform won't work.

**Comment by gaearon** [comment]
Never mind the transform.
It's extremely basic and won't help us.

I don't know how to fix this.
I tried fiddling more with prototypes but I'm afraid I'm out of my depth here.

I'd say we likely won't support IE 9 and IE 10 as dev environment anymore.

**Comment by nhunzaker** [comment]
Dropping <= IE10 support is fine by me as long as it's done in a clean way. I would love for browsers that don't have access to `__proto__` to not receive hot-loading treatment and display a warning in the console instead if at all possible.

Right now I just export an environment variable in my build to disable hot loading when testing in IE10 (`HOT=FALSE npm start`) this works fine, but I'd love to not have to worry about it.

**Comment by kentor** [comment]
I agree with @nhunzaker. I'm fine with that as well, since I didn't expect the hot reloading stuff to work in IE9 anyway.

**Comment by gaearon** [comment]
Yeah let's do that. Anybody would like to make a PR?

We should have a feature test (`supportsProtoAssignment.js`) and if it fails, we should `console.error()` a warning and ignore `update()` calls.

We should also find a way to mock the feature test for unit tests.

**Comment by nhunzaker** [comment]
I probably can't get to it until Thursday, but I'd be happy to dig in.

**Comment by gaearon** [comment]
I added you to collabs, feel free to work in a branch. Don't commit to master. ;-)

**Comment by SimenB** [comment]
Only supporting hit reloading in newer browsers is perfectly fine for me as well! 
Would it be possible to set a target for ie8 and not ie9? :grinning:

**Comment by gaearon** [comment]
Basically we'll just give you your component back if `__proto__` feature test fails so it should work on IE8 too.

**Comment by nhunzaker** [comment]
Just an update here. I was hoping to achieve at least IE9 support by playing around with prototypes (maybe this stirs some inspiration):

```javascript
var prototype = Object.create(React.Component)
var proxy = Object.create(prototype)

// Instead of re-assigning __proto__, operate on prototype
```

However I get into trouble mapping the properties from the component over to `prototype`. It's a fascinating problem, but I'm definitely out of my league here.

I'm wrapping up work on testing `__proto__` support right now, something like:

```
export default function supportsProtoAssignment () {
  return Object.prototype === ({}).__proto__
};
```

Now I just need to figure out the best way to test this... 

@gaearon We can obviously do manual testing, but you have an ideas how we can automate it? I imagine a whole load of tests will fail if we run the whole suite in < IE11. Right now, the only thing that I can think of is to stub out `supportsProtoAssignment` and confirm it doesn't apply the proxy treatment.

**Comment by gaearon** [comment]
>Right now, the only thing that I can think of is to stub out supportsProtoAssignment and confirm it doesn't apply the proxy treatment.

:+1:

**Comment by nhunzaker** [comment]
Huzzah! Any follow up work I can do?

**Comment by gaearon** [comment]
@nhunzaker 

Two things:

1. I'm getting a warning running tests. I don't think the feature test works correctly because `{}` is not really expected to have `__proto__` defined—object literals don't have prototype.

2. I'm not sure what the feature test is testing. It checks whether `__proto__` is an object on the argument but it *claims* to check whether it can be reassigned (`supportsProtoAssignment`). Does IE have no `__proto__` at all, or does it only fail on reassigning? Also, why do we need an argument at all? Why not check it like this:

```js
let x = {};
let y = { supports: true };
try {
  x.__proto__ = y;
} catch (err) {}

export default function supportsProtoAssignment() {
  return x.supports || false;
};
```

(Not tested but should match the intended behavior from the name.)

I'm not sure how we'd test this behavior in the unit tests though.

**Comment by gaearon** [comment]
I think I probably solved this with https://github.com/gaearon/react-proxy/commit/d34f1219556620b9207766076ee4ec9deb112a21.

**Comment by gaearon** [comment]
Note that React Proxy 2.x isn't yet used in React Transform HMR so it'll take some time to get this available directly.

**Comment by gaearon** [comment]
I backported it to 1.x. Should be out both in 2.0.1 and 1.1.2.

**Comment by nhunzaker** [comment]
Awesome! Sorry for the extra leg work.

**Comment by gaearon** [comment]
No problem, thanks for contributing!
