### ISSUE TITLE
createClassProxy randomly returns first cached class under Safari JIT

### ISSUE THREAD

**Issue by jwpari** [gaearon/react-proxy#55]
The fix for #52 makes `createClassProxy` behave oddly when running in the Safari JIT.

From my debugging (difficult since the issue disappears when the code is not JITed -- like when running with the inspector open) the Safari JIT (I'm running Safari 9.0.3 (build 11601.4.4)) makes `baseIteratee` (called from `lodash.find`) randomly think that the find predicate `([key]) => key === Component` --  is an `Object` and not a `Function`. 

Because of this the `baseMatches` function called instead of the `([key]) => key === Component` returns the first value in `allProxies` instead of the desired class or null.  This results in components _randomly_ being replaced by other components in `react-transform-hmr`.

```
function findProxy(Component) {
  const pair = find(allProxies, ([key]) => key === Component);
  return pair ? pair[1] : null;
}
...
export default function proxyClass(InitialComponent) {
  // Prevent double wrapping.
  // Given a proxy class, return the existing proxy managing it.
  var existingProxy = findProxy(InitialComponent);
  if (existingProxy) {
    return existingProxy;
  }
...
}
```

```
function baseIteratee(value) {
  var type = typeof value;
  if (type == 'function') {
    return value;
  }
  if (value == null) {
    return identity;
  }
  if (type == 'object') {
    return isArray(value)
      ? baseMatchesProperty(value[0], value[1])
      : baseMatches(value);
  }
  return property(value);
}
```

This also occasionally results in  a stack-overflow in  `lodash.toPairs` <- `lodash.baseMatches` <- `lodash.baseIteratee` <- `lodash.find`:

```
RangeError: Maximum call stack size exceeded.
toPairs toPairs.js:25
getMatchData _getMatchData.js:11
baseMatches _baseMatches.js:11
baseIteratee _baseIteratee.js:24
find find.js:41
findProxy createClassProxy.js:58
update createClassProxy.js:137
```

**Comment by jdalton** [comment]
Related to https://github.com/gaearon/normalizr/pull/82.

**Comment by rniwa** [comment]
Thanks a lot for the bug report!  With the information provided on this issue and gaearon/normalizr/pull/82, my colleague (Saam) and I were able to determine the root cause of this bug to be [single line of code in our DFG JIT](https://trac.webkit.org/browser/trunk/Source/JavaScriptCore/dfg/DFGAbstractInterpreterInlines.h?rev=198865#L1173) and Saam post a patch on the [newly filed WebKit bug](https://bugs.webkit.org/show_bug.cgi?id=156034).

The bug is that `typeof` can sometimes return the string "object" for a Function. You can work around this bug by using `x instance Function` instead. Here's a minimum reproduction for those who are interested (credit goes to Saam): https://gist.github.com/anonymous/49715c82e834f8e2c184d35a821ec468

**Comment by jdalton** [comment]
Just a heads up `instanceof` checks will fail for functions from other realms (iframes, node `vm` module).

**Comment by jdalton** [comment]
This is now fixed. Based on your lodash dep version range you should now be pulling in v4.7.0 which avoids the JIT bug.

**Comment by jwpari** [comment]
closing as 1.1.8 pulls in 4.7.0 ( via "lodash": "^4.6.1" )  and this fixed the issue with react-proxy and react-transform-hmr randomly substituting components.
